# Generated by Django 2.2.6 on 2019-10-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.RenameField(
            model_name='library',
            old_name='library_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='library_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='library_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='library_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Library')),
            ],
        ),
    ]
