# Generated by Django 2.2.6 on 2019-10-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_auto_20191016_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='location',
            new_name='city',
        ),
    ]
