# Generated by Django 2.2.6 on 2019-10-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_auto_20191016_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='membership_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_book', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('isbn', models.CharField(max_length=50)),
                ('total_books', models.IntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Library')),
            ],
        ),
    ]
