# Generated by Django 2.2.6 on 2019-10-17 06:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_auto_20191017_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_books',
            new_name='available_stock',
        ),
        migrations.AddField(
            model_name='book',
            name='total_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.datetime(2019, 10, 17, 6, 14, 27, 258834))),
                ('date_of_return', models.DateField(default=datetime.datetime(2019, 10, 24, 6, 14, 27, 258858))),
                ('date_returned', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Book')),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Librarian')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.Member')),
            ],
        ),
    ]
