# Generated by Django 2.2.6 on 2019-10-17 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_auto_20191017_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_of_return',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 10, 1, 39, 635362)),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 10, 1, 39, 635338)),
        ),
    ]
