# Generated by Django 2.2.6 on 2019-10-17 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_auto_20191017_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_of_return',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 11, 23, 0, 198972)),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 11, 23, 0, 198948)),
        ),
    ]
