# Generated by Django 2.2.6 on 2019-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_auto_20191017_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='book_count',
            field=models.IntegerField(null=True),
        ),
    ]
