# Generated by Django 2.2.6 on 2020-01-23 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0013_member_book_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_of_return',
            field=models.DateField(default=datetime.date(2020, 1, 30)),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_date',
            field=models.DateField(default=datetime.date(2020, 1, 23)),
        ),
    ]
